name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: adopt
      - name: Prepare
        run: ./gradlew clean kotlinNpmInstall dependencies
      - name: Assemble
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew check
