name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-v2-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            gradle-v2-${{ runner.os }}
            gradle-v2-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
      - name: Prepare
        run: ./gradlew clean kotlinNpmInstall dependencies
      - name: Assemble
        run: ./gradlew :simulator:assemble
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./simulator/build/distributions
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
